src/objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>Parent_territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent territory</description>
        <label>Parent territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Child territories</relationshipLabel>
        <relationshipName>Territory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory_level__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Territory level</description>
        <label>Territory level</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TerritoryUniqCheckHandler.cls
/*
 * Created by Serhii on 02.11.2018.
 */
public class TerritoryUniqCheckHandler {
    public static void uniqCheckAfterUpdateDelete(List<Territory__c> newTriggerTerritories) {
        Map<Id, Territory__c> territoryMap = new Map<Id, Territory__c>([
                SELECT Name,Territory_level__c, Parent_territory__c
                FROM Territory__c
        ]);
        for (Territory__c terChildOld : territoryMap.values()) {
            for (Territory__c terChildNew : newTriggerTerritories) {
                if (uniqCheckName(terChildOld, terChildNew)) {
                    throw new SObjectException('Territory with this name already exist.');
                }
            }
        }
    }

    public static Boolean uniqCheckName(Territory__c terChildOld, Territory__c terChildNew) {
        return terChildOld.Parent_territory__c == terChildNew.Parent_territory__c &&
                        terChildOld.Name == terChildNew.Name &&
            //            terChildOld.Territory_level__c == terChildNew.Territory_level__c &&
                        terChildOld.id != terChildNew.id;
    }
}